### PR TITLE
Adding ESlint code formatting

### PR DESCRIPTION
**Pull request by IVIURRAY**
Adding AirBnb ESlint formatting to dev dependencies

1. Go to this branch
2. `npm i` (maybe need to remove the `/node_modules` folder as there is lots of mess in there)
3. `eslint src/path/to/file` or to auto fix problems then run `eslint src/path/to/file --fix`

4. If using VSCode, then enable the [ESlint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)

Also `node_modules`/`package_lock.json` is a mess - so I reinstalled them.

### CODE REVIEW

**Comment by cappe** [comment]
I gives this thumps up. Simple but efficient. Since this has effects on everyone and the whole project, I won't be merging this immediatelly. I want at least one other lead to chime in and review this first.

Good job!

**Comment by IVIURRAY** [comment]
Cheers guys - this will require us to rename all our JSX files from footer.js to footer.jsx.

I’m happy to raise another review which is just a formatted code review.

I think the easiest way to do this would be;
1. Everyone merge into frontend/staging
2. Merge in this review
3. I merge in a formatted code review
4. Everyone carries on and and beaches off again

I’m online most of the GMT timezone so just ping me when you want this to happen.

**Comment by cappe** [comment]
I think the formatted code should be merged along with this PR. If this is merged now as is, without fixing the formatting, people start fixing linting errors uncontrollably here and there. That'd create a merge conflict nightmare haha.

I'd encourage running fixes here and when ready, just merge that it.

**Comment by mikirejf** [comment]
> I think the formatted code should be merged along with this PR. If this is merged now as is, without fixing the formatting, people start fixing linting errors uncontrollably here and there. That'd create a merge conflict nightmare haha.
> 
> I'd encourage running fixes here and when ready, just merge that it.

We could just organically migrate the codebase using pre-commit hooks. Eslint would need to pass for staged files if you would want to commit...

**Comment by IVIURRAY** [comment]
> > I think the formatted code should be merged along with this PR. If this is merged now as is, without fixing the formatting, people start fixing linting errors uncontrollably here and there. That'd create a merge conflict nightmare haha.
> > I'd encourage running fixes here and when ready, just merge that it.
> 
> We could just organically migrate the codebase using pre-commit hooks. Eslint would need to pass for staged files if you would want to commit...

I don't know how to do this but this this is a really good idea! - Someone make a trello task. It will need to be an admin though as github permissions.

**Comment by mikirejf** [comment]
@IVIURRAY I can do it. I've created the ticket: https://trello.com/c/nlu92ust/50-add-prettier-and-config-pre-commit-hooks-to-lint-and-format

I also assigned you to the https://trello.com/c/nmUKPsJ2/46-add-tooling-for-code-formatting and moved it to "done" since it’s been finished.

**Pull request merged**
