### PR TITLE
Login Form Dialog

### PR DESCRIPTION
**Pull request by bchehraz**
- Removed /login from route in App.js
- Moved Login form into its own component
- Removed login.js from /pages
- Added google/fb icons
- Modified LoginForm component to match mockup

Link to Trello Card: https://trello.com/c/hXKHBAXu

Any thoughts? I had a bit of trouble trying to get the login form to span out properly within the dialog box, resorted to using widths and maxWidth properties for the elements.

If needed I can move the dialog to be its own component in case we want to link it in other places and not just in the navbar component. Also, the constants/navigation.js is still unchanged and has /login in there.

### CODE REVIEW

**Comment by bchehraz** [comment]
Realized a bit late that we now have a Frontend/Staging, I think previously people were submitting PRs to be directly merged into Master

**Comment by KimEklund13** [comment]
Confirmed the UI. Dialog pops up when you click the "Login" button on the home page.
image

Email field says Email and not Email Address (from the mocks) but no biggie. Do we have text format requirements yet?

**Comment by bchehraz** [comment]
Thanks for taking a look, I just updated the label.

Also, after I rebased I noticed there were typography updates inside `theme.js` added as well as the color updates, so I went ahead and added Typography tags to some of the text. The UI will look slightly different now than the screenshot you just posted

**Comment by deranjer** [comment]
@bchehraz I merged your branch into mine, fixed some conflicts and pushed it to staging, it will get merged from there.

**Pull request closed without merging**
